//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eq.model.entitymodel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EQEntities : DbContext
    {
        public EQEntities()
            : base("name=EQEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnswerType> AnswerTypes { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<EQArea> EQAreas { get; set; }
        public virtual DbSet<EQTrackingItem> EQTrackingItems { get; set; }
        public virtual DbSet<EQTrackingItemAnswer> EQTrackingItemAnswers { get; set; }
        public virtual DbSet<EQTrackingItemAnswerTemplate> EQTrackingItemAnswerTemplates { get; set; }
        public virtual DbSet<EQTrackingItemTemplate> EQTrackingItemTemplates { get; set; }
        public virtual DbSet<PersonalGoal> PersonalGoals { get; set; }
        public virtual DbSet<PersonalTrackingLog> PersonalTrackingLogs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
