//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eq.model.entitymodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQTrackingItemAnswerTemplate
    {
        public int Id { get; set; }
        public int TrackingItemId { get; set; }
        public int AnswerTypeId { get; set; }
        public string Title { get; set; }
        public Nullable<int> Point { get; set; }
    
        public virtual AnswerType AnswerType { get; set; }
        public virtual EQTrackingItemTemplate EQTrackingItemTemplate { get; set; }
    }
}
