//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eq.model.entitymodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQTrackingItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EQTrackingItem()
        {
            this.EQTrackingItemAnswers = new HashSet<EQTrackingItemAnswer>();
        }
    
        public int Id { get; set; }
        public int AreaId { get; set; }
        public string UserId { get; set; }
        public string Title { get; set; }
        public string Question { get; set; }
        public Nullable<int> OriginalTemplateId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual EQArea EQArea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EQTrackingItemAnswer> EQTrackingItemAnswers { get; set; }
    }
}
