//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eq.model.entitymodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQTrackingItemAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EQTrackingItemAnswer()
        {
            this.PersonalGoals = new HashSet<PersonalGoal>();
            this.PersonalTrackingLogs = new HashSet<PersonalTrackingLog>();
        }
    
        public int Id { get; set; }
        public int TrackingItemId { get; set; }
        public int AnswerTypeId { get; set; }
        public string Title { get; set; }
        public Nullable<int> Point { get; set; }
    
        public virtual AnswerType AnswerType { get; set; }
        public virtual EQTrackingItem EQTrackingItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalGoal> PersonalGoals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalTrackingLog> PersonalTrackingLogs { get; set; }
    }
}
