//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eq.model.entitymodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalGoal
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int AnswerId { get; set; }
        public int Goal { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual EQTrackingItemAnswer EQTrackingItemAnswer { get; set; }
    }
}
